// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_CppWinRTComponent_0_H
#define WINRT_CppWinRTComponent_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::CppWinRTComponent
{
    struct IGLControl;
    struct GLControl;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::CppWinRTComponent::IGLControl>{ using type = interface_category; };
    template <> struct category<winrt::CppWinRTComponent::GLControl>{ using type = class_category; };
    template <> struct category<winrt::CppWinRTComponent::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::CppWinRTComponent::GLControl> = L"CppWinRTComponent.GLControl";
    template <> inline constexpr auto& name_v<winrt::CppWinRTComponent::XamlMetaDataProvider> = L"CppWinRTComponent.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::CppWinRTComponent::IGLControl> = L"CppWinRTComponent.IGLControl";
    template <> inline constexpr guid guid_v<winrt::CppWinRTComponent::IGLControl>{ 0x6015C713,0x162C,0x58BC,{ 0xB3,0xEF,0xEF,0x6D,0xE8,0xEB,0x1F,0x77 } }; // 6015C713-162C-58BC-B3EF-EF6DE8EB1F77
    template <> struct default_interface<winrt::CppWinRTComponent::GLControl>{ using type = winrt::CppWinRTComponent::IGLControl; };
    template <> struct default_interface<winrt::CppWinRTComponent::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::CppWinRTComponent::IGLControl>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall Init(int64_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_CppWinRTComponent_IGLControl
    {
        auto Init(int64_t hWndParent) const;
    };
    template <> struct consume<winrt::CppWinRTComponent::IGLControl>
    {
        template <typename D> using type = consume_CppWinRTComponent_IGLControl<D>;
    };
}
#endif
