// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_CppWinRTComponent_GLControl()
{
    return winrt::detach_abi(winrt::make<winrt::CppWinRTComponent::factory_implementation::GLControl>());
}
WINRT_EXPORT namespace winrt::CppWinRTComponent
{
    GLControl::GLControl() :
        GLControl(make<CppWinRTComponent::implementation::GLControl>())
    {
    }
}
